import Head from "next/head";
import Header from "@/components/Header/";
import Footer from "@/components/Footer";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Layout({ children, metaTitle, metasDescription }) {
  return (
    <>
      <Head>
        <title>Create Next App - {metaTitle}</title>
        <meta name="description" content={metasDescription || "Generated by create next app"} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </>
  );
}
